cb.settings_choices = [
{ name: 'onmsg',
  type: 'str',
  defaultValue: 'Spanks have been enabled',
  label: 'Spanks On Notice'
},
{ name: 'offmsg',
  type: 'str',
  defaultValue: 'Spanks have been disabled',
  label: 'Spanks Off Notice'
},
{ name: 'sponmsg',
  type: 'str',
  defaultValue: 'A Special Deal on Spanks has Started!! Spanks are Now 1/2 off!! :leiaspanks',
  label: 'Special Deal Notice'
},
{ name: 'spoffmsg',
  type: 'str',
  defaultValue: 'The Deal on Spanks has Ended! Total Spanks: spanks',
  label: 'Special Deal Over Notice'
},
{ name: 'amt',
  type: 'int',
  defaultValue: '5',
  label: 'Spanks Amount'
},
{ name: 'addtip',
  type: 'int',
  defaultValue: '11',
  label: 'Add Spanks Amount'
},
{ name: 'addmsg',
  type: 'str',
  defaultValue: 'tipper Tipped to add Spanks Total Spanks: spanks',
  label: 'Add Spanks Notice'
},
{ name: 'subtip',
  type: 'int',
  defaultValue: '12',
  label: 'Sub Spanks Amount'
},
{ name: 'submsg',
  type: 'str',
  defaultValue: 'tipper Tipped to sub Spanks Total Spanks: spanks',
  label: 'Sub Spanks Msg'
},
{ name: 'sptip',
  type: 'int',
  defaultValue: '5',
  label: 'Special Spanks Amount'
},
{ name: 'spmsg',
  type: 'str',
  defaultValue: 'tipper Tipped for AFK Spanks Total Spanks: spanks',
  label: 'Special Spanks Notice'
},
{ name: 'color',
  type: 'str',
  defaultValue: '#80FFE0',
  label: 'Notices Color'
}]

var spanks;
spanks = 0;
var spankson = true
var spon = true

cb.onMessage (function(msg){
 if (msg['m'].startsWith('!')){
  msg['X-Spam'] = true
  } else {return msg
  }
  if (msg['m'] == '!spanks'){
   cb.chatNotice('Spanks Total: ' + spanks, msg['user'], cb.settings.color)
  }
  if (msg['m'] == '!spanksleaderboard'){
  }
  if (msg['user] == cb.room_slug || msg['is_mod']){
   if (msg['m'] == '!spankson'){
    spankson = true
    cb.chatNotice(cb.settings.onmsg, '', cb.settings.color)
   }
   if (msg['m'] == '!spanksoff'){
    spankson = false
    cb.chatNotice(cb.settings.offmsg, '', cb.settings.color)
   }
   if (msg['m'] == '!afkon'){
    spon = true
    cb.chatNotice(cb.settings.sponmsg, '', cb.settings.color)
   }
   if (msg['m'] == '!afkoff'){
    spon = false
    cb.chatNotice(cb.settings.spoffmsg, '', cb.settings.color
   }
   if (msg['m'].startsWith '!spanked'){
   }
   if (msg['m'].startsWith 'addspanks'){
   }
  }
 }
})
